### ISSUE TITLE
Doesn't work on Chromium

### ISSUE THREAD

**Issue by mezzofort3** [magwo/elevatorsaga#102]
The code window loads, but not the elevators.

**Comment by tcort** [comment]
Can you provide a little more information about your environment... OS, version of Chromium, etc. Also, are you trying to play via [play.elevatorsaga.com](http://play.elevatorsaga.com/) or are you hosting the files elsewhere? If elsewhere, is it the latest commit from the master branch?

FWIW, I tried Chome 49.0.2623.87 on Linux/amd64 and it works fine for me.
