### ISSUE TITLE
Is this repo will be maintend 

### ISSUE THREAD

**Issue by CfirTsabari** [magwo/elevatorsaga#112]
I saw this game when surfing the web and and my friend(which is autistic) loved this game (he likes elevators) very much.
But my friend doesn't know English and i want to translate this game to Hebrew.
I want to make it multi language support.
Mainly I see two parts I need to work on:

1 - The site UI - Controls, documentation and such.
2 - The code which is pure JS and this might be a little tricky.

So my question is : will this repo be maintained? any point in creating pull requests and such?

**Comment by shoheihagiwara** [comment]
> So my question is : will this repo be maintained? any point in creating pull requests and such?
I was wondering the same.

@magwo I don't know if this is the right place to ask for this, but could you make me a collaborator so that I can maintain this repository? I really like your Elevator Saga! Although I haven't any experience collaborating on someone's project, I would love an opportunity to contribute to this project :)  Thanks in advance!

**Comment by ProBeta1** [comment]
@CfirTsabari , @shoheihagiwara its an open source project . So we all can collaborate and make it even more better !

**Comment by magwo** [comment]
Hi all,

sorry for not replying sooner. I don't intend to continue develop this project or review pull requests. After "finishing it" I was a little burnt out and I felt that the game was in a sufficiently playable state to be considered finished.

I would like to keep the original version on the github pages hosted domain, but I fully condone forks, translations and variations of the game! The game was developed to spark joy and delight about programming, and it brings a smile to my face to see others making derivative works in the same spirit.

**Comment by magwo** [comment]
However: If there are prominent forks out there, I will gladly link to them from the README in this repo.
