### ISSUE TITLE
I don't get this error

### ISSUE THREAD

**Issue by Rodsevich** [magwo/elevatorsaga#118]
![error](https://i.imgur.com/ZyduRkr.png)
I'm not working with JS from some years ago, but I don't get the error, it's taken as in the API docs

**Comment by adisib** [comment]
I think you need to use a for...of loop instead of a for...in loop.

**Comment by Rodsevich** [comment]
Seems it's to be var floor _of_ floors

**Comment by Rodsevich** [comment]
thanks!!
