### ISSUE TITLE
Specify which passenger waited too long.

### ISSUE THREAD

**Issue by pppery** [magwo/elevatorsaga#135]
When solving max waiting time problems, I ran into the problem that I suddenly get "challenge failed" without it being clear to me who caused the challenge to fail. Showing which passenger exceeded the max waiting time would make things clearer.

**Comment by avodonosov** [comment]
I agree. 

Even with my patch for https://github.com/magwo/elevatorsaga/issues/34 which allows me to replay the same run multiple times it's difficult to see who exactly waited too long.

**Comment by avodonosov** [comment]
Interesting that style.css has yellow and red color for disappointed and frustrated users:
https://github.com/magwo/elevatorsaga/blob/e0c55bf8cf59243c32dc371b2cc7b2e3ec1664af/style.css#L245

Although nowhere in the code those styles are set.

Looks like that is a not completed feature.

**Comment by pppery** [comment]
Closing as a duplicate of #77

**Comment by avodonosov** [comment]
@pppery , #77 is indeed talks about the same thing, although the titles are different: the current issue only speaks about the oldest passenger, while #77 title means wait time for every passenger.
