### ISSUE TITLE
[RFC] Adjustable editor font size or more browser zoom friendly layout.

### ISSUE THREAD

**Issue by dontdieych** [magwo/elevatorsaga#16]
If I use browser zoom - around 130% - then it exceed screen.

**Comment by dontdieych** [comment]
Forgot about thanks for this fun game!

**Comment by magwo** [comment]
Thank you. :)

**Comment by magwo** [comment]
Upped the font a little bit and the width and invisible padding has been tweaked. Works well enough?

**Comment by dontdieych** [comment]
Much better.

Thanks.
