### ISSUE TITLE
level #7 starts with 6 moves

### ISSUE THREAD

**Issue by nichdiekuh** [magwo/elevatorsaga#20]
No matter what I do, even with the default script from level one, as soon as I press start the moves counter increases to six, before I get a change to call goToFloor() on any elevator

**Comment by magwo** [comment]
https://github.com/magwo/elevatorsaga/commit/9d40ac0b2a45c7f4dceeb8767856ccb12404878b

**Comment by nichdiekuh** [comment]
Great, thank you! Hope you enoyed being on the HN Frontpage ;)

**Comment by magwo** [comment]
Haha sure! My 15 minutes of internet fame.. ;)
