### ISSUE TITLE
horizontal scroll

### ISSUE THREAD

**Issue by marado** [magwo/elevatorsaga#22]
Horizontal scrolls are ugly. And inconvenient.
Unless there's a good reason to have such a large lobby (there isn't on level 1 and 2), maybe you could make this work an an 1280 X 800 screen without the need to have the horizontal scroll...

**Comment by magwo** [comment]
https://github.com/magwo/elevatorsaga/commit/cf160af212bb6b057ad7ae13a567545dae881559
