### ISSUE TITLE
add a proper way of setting elevators as operating or not

### ISSUE THREAD

**Issue by marado** [magwo/elevatorsaga#24]
At this moment, if an elevator doesn't listen to any event, then people treat that elevator as "out of order" (not existing). But there should be a better way of defining how many elevators are working, or at least document how to make this happen (possibly by the same way I described as doing).

**Comment by magwo** [comment]
I think this has been fixed by https://github.com/magwo/elevatorsaga/commit/6ce62a1481d8df5cfd73f45851cde46ff68d41e1

**Comment by magwo** [comment]
Or well, at least people will get into a stand-still elevator..
