### ISSUE TITLE
Game freeze with loop on floors

### ISSUE THREAD

**Issue by seigneurcanard** [magwo/elevatorsaga#27]
I have started making a for loop for floors and it seems to have frozen the animation :

    {
    init: function(elevators, floors) {
        var calledElevator = [];
        var calledElevatorUp = [];
        var calledElevatorDown = [];
        var elevator = elevators[0]; // Let's use the first elevator

        for (i = 0; i < floors.length; i++) { 
            floors[i].on("up_button_pressed", function() {
                calledElevatorUp.push(floors[i].floorNum);
                calledElevator.push(floors[i].floorNum);
            })

            floors[i].on("down_button_pressed", function() {
                calledElevatorDown.push(floors[i].floorNum);
                calledElevator.push(floors[i].floorNum);
            })
        }

    },
    update: function(dt, elevators, floors) {
        // We normally don't need to do anything here
    }
    }

**Comment by ffrulani** [comment]
You should pass the loop counter (variable "i") as a parameter of the anonymous function.

http://stackoverflow.com/questions/750486/javascript-closure-inside-loops-simple-practical-example

**Comment by magwo** [comment]
Yep @ffrulani is correct, this is a common JS closure bug. Although I wished the game could give better error messages.

I would recommend to use _.each() instead. That way you don't need an iteration variable and you don't get the closure binding problem. See https://lodash.com/docs#forEach
