### ISSUE TITLE
Floor indicators do not match elevator.goingUpIndicator()/ elevator.goingDownIndicator()

### ISSUE THREAD

**Issue by leaVael** [magwo/elevatorsaga#31]
Hey there, 
the visually displayed floor indicators ( as introduced by pull request #28) seem to be reversed -when logging elevator.goingUpIndicator() or elevator.goingDownIndicator() I get the opposite of what is visually displayed.

**Comment by MarianoGappa** [comment]
I have this same behaviour.

**Comment by execdd17** [comment]
+1

**Comment by LiraNuna** [comment]
+1, this confused me since people who go down will not go into an elevator that looked like it's going up with the indicators

**Comment by magwo** [comment]
https://github.com/magwo/elevatorsaga/pull/32
