### ISSUE TITLE
Add direct way to get an array of pressed floor numbers

### ISSUE THREAD

**Issue by sim642** [magwo/elevatorsaga#35]
When people press the floor buttons in the elevator the little numbers light up visually to indicate which floors have been pressed but there is no way to directly get an array of those numbers in the code. Instead one would have to manually keep track of all those which is rather inconvenient, especially when the system actually already exists.

**Comment by furtive** [comment]
Isn't that the one of the key points of the game, learning how to maintain state?

**Comment by sim642** [comment]
@furtive, if it were all about maintaining state, then we should strip anything already there that provides that too, such as .currentFloor(), because the player can obviously keep track of it through events
