### ISSUE TITLE
Add livescript/elm/purescript/whatever support

### ISSUE THREAD

**Issue by shouya** [magwo/elevatorsaga#38]
This is a game I have in mind for long. I was really excited to see it finally appeared. While as I tried several levels and the code scale grows, I found it really difficult for me to write correct Javascript, as I'm, in most time, a Haskell/Racket/Ruby programmer.

Javascript is a language full of traps that drives me crazy on it. Most of my time were wasted on debugging with Javascript's terrible design and I could not focus well on the algorithm, which is really not what I wanted. You know, as in Javascript, weakly typed, everything just executes without yielding any error messages, while it's just not doing what I think it should do and gives me a totally wrong result, or it stuck at some point. These problems are hard to debug.

I don't even mind to learn a language that compiles to Javascript for just this game because I really want to play it well. Anyway, if you don't mind to add such functionality to allow players to write code in a language that compiles to Javascript, I would suggest Livescript. Though purescript is what I want most (because it's mostly the same as Haskell), but Livescript is much more popular and well supported.

Thank you anyway for bringing such a wonderful game. I was just a little bit tried on struggling with those Javascript traps :sob:

**Comment by shouya** [comment]
Alright, ignore this issue. I started to write in livescript and compiles it into javascript myself. :smile:

**Comment by magwo** [comment]
Ah right. I considered it, as I really like CoffeeScript myself. However, as you say it's entirely possible to do the compilation by yourself.. so the added value isn't very great with regards to development effort and complexity for the project.
