### ISSUE TITLE
Challenge Ideas

### ISSUE THREAD

**Issue by taylorhakes** [magwo/elevatorsaga#40]
I thought it might be good to get a thread going of interesting additional challenges/levels. Here are some of my ideas.

- Random number of people per elevator (some allow 2, others 6, etc)
- People's weight affect how many people per elevator. Currently 4 people can always fit per elevator. Have some really heavy people so only 2 can get on the elevator.
- [Double decker elevator](http://en.wikipedia.org/wiki/Double-deck_elevator) (The elevator visits 2 floors at once. This could be extended to triple decker, etc.)
- [Destination dispatch elevators](http://en.wikipedia.org/wiki/Destination_dispatch) (People press the floor in addition to calling the elevator. A lot of new buildings have these.)
- Elevators out of service (Sometimes the elevator is broken)

**Comment by magwo** [comment]
Some of these are interesting ideas. As I wrote in the (excellent) pull request you made, I want to keep complexity at a minimum while still having an interesting game.

At the very least, added complexity should make the game much more interesting to play.

Some of these ideas, like different weight of people, don't really add much to the enjoyment, while making the code (and playing experience) more complex. Already I'm not sure if the weight of people is an interesting concept at all. Elevators out of service doesn't really affect the algorithmic challenge much, it's just one less elevator to use, and potentially confuses players writing the code, not realizing that an elevator can be out of service.

I'm thinking that additional challenges, at least for now, would focus more on the algorithmic fitness and different optimizations, like minimizing average wait time and combining different constraints to complete a challenge.

**Comment by taylorhakes** [comment]
I am just throwing out some ideas. I am definitely not expecting all or any of these to be used. 

I have finished the game myself and so have several of my friends. I agree that being simple is better, but I think that anyone who finishes the game already (beat level 16) has an understanding of the game. Adding additional obstacles won't be an issue, as long as they are added incrementally. In it's current state you can write one or two algorithms and pass all the levels. It gets interesting when you need to modify the algorithm because the new level needs a new algo to win.

Different weight users: I think it makes people use the loadFactor() function. Currently you can be sure that 4 people will be in the elevator.

Out of service elevators: I think this is a really interesting concept (and it happens in real life). The player needs to check if the elevator is out of service and not send it to the floor. When the elevator comes back in service, the player needs to acknowledge it and put it back in the rotation. Obviously this wouldn't happen until later challenges (probably after 16). I don't think it would be difficult to understand. You could put a big red X on the elevator.

All my ideas were for later levels. Once the person understands the game. Currently I think the game lasts around 3-4 hours for an average developer. I think it would be great to have 100+ challenges. It's going to be difficult to create many more the current setup and no additional obstacles.

**Comment by magwo** [comment]
Yeah those are good points.

Something interesting would be to have a difficult challenge with one small and one large elevator, where you probably need to serve the upper floors with the large one.

**Comment by magwo** [comment]
Although I'm leaning towards scrapping the concept of weight, and just counting users etc. The weight concept doesn't really make it more interesting than just userCount and maxUserCount or such.

**Comment by magwo** [comment]
@taylorhakes Added some nice things in https://github.com/magwo/elevatorsaga/commit/da03f5e6a784cdb1357cb0ba837c8065e3b30772

**Comment by taylorhakes** [comment]
Very nice additions. Definitely adds some difficulty

**Comment by quassy** [comment]
> Destination dispatch elevators (People press the floor in addition to calling the elevator. A lot of new buildings have these.)

This would be a nice addition for an "easy" mode with each challenge. So just keep the challenges, but allow a checkbox to have people pressing their destination.

**Comment by taylorhakes** [comment]
I would argue that destination dispatch elevators don't make the game any easier. It gives you more information, but the elevator can now move people more efficiently. The number of people per challenge can be higher (number of steps lower, etc.) because your elevators can now be smarter.

**Comment by quassy** [comment]
Well if you leave the goals the same it would be easier. If you would adapt the goals and make them harder then before it would be more work as you would have to deal with more information.

**Comment by magwo** [comment]
Closing as part of an issue cleanup. Please open specific feature requests, one per feature, if there's something in particular that you would like to see!
