### ISSUE TITLE
Erroneous handling of floor

### ISSUE THREAD

**Issue by asm0dey** [magwo/elevatorsaga#42]
Code like
```javascript
    for (i = _i = 0, _len = floors.length; _i < _len; i = ++_i) {
      floor = floors[i];
      floor.on('up_button_pressed down_button_pressed', function(event) {
          console.log(event)
          console.log(i)
        activeFloors.push(i);
      });
    }
```
reports one floor every time. In my case it's 8

**Comment by asm0dey** [comment]
Looks like all events are being binded to one floor

**Comment by marado** [comment]
No, your iterator is the one that reports '8'. You shouldn't be using 'i'
in the event handler function, try 'this' to get the floor object instead

**Comment by asm0dey** [comment]
You're right, this works. But it looks like strange behaviour for me. Binding event listener isn't async action, is it?

**Comment by magwo** [comment]
https://github.com/magwo/elevatorsaga/issues/27
