### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by SignpostMarv** [magwo/elevatorsaga#45]
Repo has no explicit license

**Comment by magwo** [comment]
What would you recommend? I do not mind a discussion on this topic. I don't know much about licenses.

**Comment by segiddins** [comment]
I personally like MIT -- it's very permissive.

**Comment by taylorhakes** [comment]
+1

**Comment by SignpostMarv** [comment]
MIT would be a good suit (you're using MIT-licensed libraries, for example).

for more info, http://choosealicense.com/ seems like a good place to start?

**Comment by magwo** [comment]
Yep!

**Comment by magwo** [comment]
https://github.com/magwo/elevatorsaga/commit/26015ef2fbe59a182ec6b7dc27b8901b7b319f66
