### ISSUE TITLE
Simulate random people behavior

### ISSUE THREAD

**Issue by Ghannid** [magwo/elevatorsaga#56]
First, congratulations I been wanting to simulate elevators for a long time, and this game covers so much of the fun of it.

Could the core simulate some random behaviored people? I mean people flooding the elevator (over capacity) or who presses buttons twice, or buttons outside the current scheduled movement, might trick some implementations.

**Comment by magwo** [comment]
Thanks for your feedback! These are interesting suggestions but at the moment I think added randomness and faulty situations would distract from the algorithm-creation focus of the game.
