### ISSUE TITLE
Hide top-floor up button and bottom-floor down button

### ISSUE THREAD

**Issue by roryokane** [magwo/elevatorsaga#60]
The floor call indicator arrows currently look like this (on [challenge 1](http://play.elevatorsaga.com/#challenge=1)):

![current floor call indicators](https://cloud.githubusercontent.com/assets/79168/5946298/83d97bc4-a6e9-11e4-9ce9-4deb1f2248f3.png)

But it doesn’t make sense for floor 0 to have a down button, or the topmost floor to have an up button. You can’t go any farther, and thankfully the simulated users never press that button.

Thus, I suggest that those two impossible arrows be hidden:

![suggested floor call indicators](https://cloud.githubusercontent.com/assets/79168/5946313/8e2cb9ba-a6e9-11e4-935e-cf298c5db787.png)

Hopefully, hiding those arrows will guide programmers into handling the floor call button presses better, because they will instantly realize that no users will ever press those two hidden buttons.

You can hide the icons with the CSS `visibility: hidden;` so that the top floor’s down indicator is still aligned with other down indicators. The other part of the implementation is changing the [`floor-template` in `index.html`](https://github.com/magwo/elevatorsaga/blob/0b04f693e73c0cd5e106c8b94922c10c3bf8a1e2/index.html#L35) so that just those two indicators get the appropriate class added to them, and possibly also changing the data that is [passed to that template](https://github.com/magwo/elevatorsaga/blob/0b04f693e73c0cd5e106c8b94922c10c3bf8a1e2/presenters.js#L61).

**Comment by magwo** [comment]
Yeah, agree.

**Comment by magwo** [comment]
https://github.com/magwo/elevatorsaga/commit/6b429399a4e1de797a61a639fdbc6d219b768e3e
