### ISSUE TITLE
elevator.on "passing_floor" gives floorNum = -1

### ISSUE THREAD

**Issue by threldor** [magwo/elevatorsaga#64]
I have found that the passing_floor event sometimes has floorNum = -1
Often (every 200s or so) on the challenge 18 when the elevator comes from a high floor to ground floor it seems that the passing_floor is triggered twice

using the code snippet similar to below the log shows

```
LOG
prevfloor:1 floorNum:0 dir:down
prevfloor:0 floorNum:-1 dir:down
```

```
elevator.on("passing_floor", function(floorNum, direction) {
    console.log('prevfloor:' + prevFloor + ' floorNum:' + floorNum + ' dir:' + direction);
    prevFloor = floorNum;
});
```

**Comment by magwo** [comment]
Pretty sure this is related to https://github.com/magwo/elevatorsaga/issues/61
