### ISSUE TITLE
Game stops running randomly with this solution

### ISSUE THREAD

**Issue by dariusdamalakas** [magwo/elevatorsaga#83]
Hi,

Awesome game.  Not sure if this is a bug in my solution or in game code, but challenge 5 stops randomly after some time. I.e. it never reaches success or fail screen, elevators just stop in the middle of transition doing nothing. Floor buttons work fine, but game time does not progress.

Clicking 'apply' resets the game, but it hangs again after some time.

http://play.elevatorsaga.com/#challenge=5

    {
    init: function(elevators, floors) {
        
        var onIdle = function(elev){
            elev.goToFloor(0);
        };
        
        var onFloorButtonPressed = function(elev, floorNum){
            elev.goToFloor(floorNum);
        }
        
        var onPassingFloor = function(elev, floorNum, direction){
            var pressed = elev.getPressedFloors();
            if (pressed.length > 0) 
            {
                if (pressed.lastIndexOf(floorNum) > 0)
                    elevator2.goToFloor(floorNum, true);
            }
        }
        
        var setUp = function (el){
            el.on("idle", function() {
                onIdle(el)
            });
        
            el.on("floor_button_pressed", function(floorNum) {
                onFloorButtonPressed(el, floorNum);
            })
        
            el.on("passing_floor", function(floorNum, direction) { 
                onPassingFloor(el, floorNum, direction);
            });
        }
        
        setUp(elevators[0]);
        setUp(elevators[1]);
        setUp(elevators[2]);
        setUp(elevators[3]);
            
    },
    update: function(dt, elevators, floors) {
        // We normally don't need to do anything here
    }
    }

**Comment by dariusdamalakas** [comment]
Ah, variable not defined! ('elevator2')

**Comment by larva** [comment]
I think this issue brings up a good point though -- it would be nice to be able to show these kinds of problems more plainly rather than have the game partially freeze.

**Comment by magwo** [comment]
Yes. Improved error messages is a desired improvement. I currently do not have any ideas or plans on how.

**Comment by larva** [comment]
I was thinking that it would be great to run a javascript interpretter inside the game itself. It would probably be easier to report these issues plus you could add indicators for which line of code each elevator was executing -- perhaps by adding a "breakpoint" column for each elevator and having a little indicator hop to the currently executing line.
