### ISSUE TITLE
Add a `direction` method to elevator API?

### ISSUE THREAD

**Issue by yxiong** [magwo/elevatorsaga#84]
I'm wondering whether it is possible to add a `direction` method to the elevators, which returns `"up"`, `"down"` or `"stopped"`, so that the programmers can use this information to make better decision.

I understand that current `passing_floor` event provides `direction` as an argument to the callback, but I hope this information to be more accessible on other events as well (say when a floor's up button is pressed, programmers might want to know which elevator is coming to its direction).

I see that programmers can try to manage this information themselves with `goingUpIndicator` and `goingDownIndicator`, but the purpose of those indicators is to tell passengers whether to get on or not. It would be nice to provide the `direction` to the programmer, so that they can easily set the indicators accordingly.

**Comment by magwo** [comment]
Ah ok. So what you want is something that says, basically, if the elevator velocity is positive or negative?

To minimize confusion, I would prefer to expose a velocity value instead of "direction". Then you can check whether the velocity is negative or positive. Would that be helpful?

**Comment by yxiong** [comment]
Yes, that's exactly what I want. Thanks!

BTW, in the future, different elevator could even have different velocity (just as they have different `maxPassengerCount`), which will give us one more dimension to optimize. Should be fun! :)
