### ISSUE TITLE
passing_floor not working

### ISSUE THREAD

**Issue by ToyYoda** [magwo/elevatorsaga#88]
My Code is the following:
{
    init: function(elevators, floors) {
        var elevator = elevators[0];
        elevator.on("idle",function(){
            elevator.goToFloor(floors.length -1);
        });
        
        elevator.on("passing_floor",function(floor,direction){
            console.log("Elevator 0 passing_floor " + floorNum + ". Direction: " + direction);
        });
    },
    update: function(dt, elevators, floors) {
        // We normally don't need to do anything here
    }
}

Somehow, the "passing_floor" event is not triggered while the elevator is going from floor 0 to the top. Another thing that makes me wonder is: The elevator returns to the bottom.
Any explaination? Didn't I understand how passing_floor works?

**Comment by magwo** [comment]
Thanks for your report. Seems like a bug introduced in the recent optimisations.. will take a look.

**Comment by magwo** [comment]
Appears to be caused by having an error in your code, then fixing it and then pressing Apply. Messes up the current_floor logic it seems. Not sure why yet.

**Comment by bstojkovic** [comment]
I'm also experiencing this issue. My code:

```
{
    init: function(elevators, floors) {
        for (var i = 0; i < elevators.length; i++) {
            let elevator = elevators[i];
            elevator.on("idle", function() {
                elevator.goToFloor(7);
                elevator.goToFloor(0);
            });
            elevator.on("passing_floor", function(floorNum, direction) {
                var pressed_floors = elevator.getPressedFloors();
                if (floorNum in pressed_floors) {
                    console.log('Floor:',floorNum);
                    console.log(pressed_floors);
                    elevator.goToFloor(floorNum, true);
                }
            });
        }
    },
        update: function(dt, elevators, floors) {
            // We normally don't need to do anything here
        }
}
```

I am on challenge 4 and it doesn't print out the floors it's passing, only first 3 floors (0-2).
