### ISSUE TITLE
Unbind events?

### ISSUE THREAD

**Issue by tjwudi** [magwo/elevatorsaga#97]
Is there any API like `jQuery.off()` that unbinds all event listeners?

**Comment by Lexicality** [comment]
```js
elevator.off('*');
```
See also:
- [The Unobservable Library][unobservable]
- [Riot.Observable][riot.observable] which it is based on

[unobservable]: https://github.com/magwo/unobservable
[riot.observable]: http://riotjs.com/api/observable/#off

**Comment by tjwudi** [comment]
Thanks! @Lexicality
